language: generic

services:
  - docker

script:
  - sudo mkdir report && sudo chown 1000:1000 report
  - docker run -t -v $(pwd)/report:/zap/wrk/:rw owasp/zap2docker-stable zap-baseline.py -t http://34.255.30.110:32771 -r testreport.html || true
  - cat ./report/testreport.html
